### ISSUE TITLE
Patch [ACSD-46988]: Missing dependencies to symfony/intl package

### ISSUE THREAD

**Issue by mrodespin** [magento/quality-patches#92]
This patch adds couple of dependencies to the package `symfony/intl `which is not included in a Magento 2.4.5 basic installation and opening the admin panel we are getting the following error

`[2022-12-01T08:57:39.142767+00:00] main.CRITICAL: Error: Class "Symfony\Component\Intl\Currencies" not found in /magento/vendor/magento/framework/Currency/Data/Currency.php:303`

**Comment by agorbivskyi** [comment]
@mrodespin in order to solve this issue:

> For On-premises users:
> 
> Run: composer require symfony/intl:"~5.4.11"
> For Cloud users:
> 
> Run: composer require symfony/intl:"~5.4.11"
> Push composer.json and composer.lock files to the git repository along with the patch file.

You may check more details regarding the issue in https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/support-tools/patches/v1-1-21/acsd-46988-graphql-currency-api-request-returns-null-values.html
As a "best practice" we recommend to check appropriate articles before applying patches since it may contain additional instructions/steps.
